# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Customize git branch display
[git_branch]
format = "[$symbol$branch]($style) "
style = "bold purple"

# Customize git status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold yellow"

# Disable the cloud module to remove the cloud emoji
[gcloud]
disabled = true

[aws]
disabled = true

[azure]
disabled = true
